### ISSUE TITLE
Unable to compile gqt from source

### ISSUE THREAD

**Issue by fierytortilla** [ryanlayer/gqt#43]
I have followed the instructions in the installation section carefully, but whenever I run `make`, I get the following error:

`/bin/ld: /home/azureuser/vcf-browsers/htslib/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha256@@OPENSSL_1_1_0'
/bin/ld: /lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:73: ../bin/read_binary_uints] Error 1
make[1]: Leaving directory '/home/azureuser/vcf-browsers/gqt/src'
make: *** [Makefile:8: all] Error 2
`

I have deduced that this is a problem with the openssl package, but I cannot figure out how to solve it. I have tried downloading different versions of the openssl library, but nothing seems to work. I am working on an Ubuntu 20.04 on a Azure VM.
